services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postly
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

volumes:
  pgdata:
